/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Street_Clock.h"
#include "WindowDLG.h"
#include "Buttons.h"
#include <stdio.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x04)
#define ID_BUTTON_2 (GUI_ID_USER + 0x05)
#define ID_BUTTON_3 (GUI_ID_USER + 0x06)
#define ID_BUTTON_4 (GUI_ID_USER + 0x07)
#define ID_BUTTON_5 (GUI_ID_USER + 0x08)
#define ID_BUTTON_6 (GUI_ID_USER + 0x09)
#define ID_TEXT_0 (GUI_ID_USER + 0x0A)
#define ID_TEXT_1 (GUI_ID_USER + 0x0B)
#define ID_TEXT_2 (GUI_ID_USER + 0x0C)
#define ID_TEXT_3 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_7 (GUI_ID_USER + 0x0E)
#define ID_TEXT_4 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_8 (GUI_ID_USER + 0x10)
#define ID_TEXT_5 (GUI_ID_USER + 0x11)
#define ID_TEXT_6 (GUI_ID_USER + 0x12)


// USER START (Optionally insert additional defines)
extern STREETCLOCK_HandleStoreSettingsTypeDef sett_store;
  WM_HWIN hItem_TEXT_RTC;
  WM_HWIN hItem_TEXT_Clock;
  WM_HWIN hItem_TEXT_Note;
  WM_HWIN hItem_TEXT_State;
  WM_HWIN hItem_TEXT_GPS_Signal;
  WM_HWIN hItem_TEXT_UTC;
	WM_HWIN hItem_Text_Block;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Return", ID_BUTTON_0, 260, 205, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Save", ID_BUTTON_1, 205, 120, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Down", ID_BUTTON_2, 205, 155, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Right", ID_BUTTON_3, 260, 120, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Left", ID_BUTTON_4, 150, 120, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Up", ID_BUTTON_5, 205, 85, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_Set_RTC", ID_BUTTON_6, 205, 15, 110, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text_RTC", ID_TEXT_0, 5, 10, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Clock", ID_TEXT_1, 5, 40, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Note", ID_TEXT_2, 4, 213, 254, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_State", ID_TEXT_3, 5, 189, 254, 25, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button_Set_Clock", ID_BUTTON_7, 205, 49, 110, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text_GPS_Signal", ID_TEXT_4, 5, 85, 156, 24, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button_Set_UTC", ID_BUTTON_8, 140, 44, 34, 21, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text_UTC", ID_TEXT_5, 142, 10, 56, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Block", ID_TEXT_6, 272, 175, 21, 26, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00808000);
    //
    // Initialization of 'Button_Return'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Ret");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Button_Save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Save");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Button_Down'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "Down");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Button_Right'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "Right");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Button_Left'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetText(hItem, "Left");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Button_Up'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "Up");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Button_Set_RTC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hItem, "Set RTC");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Text_RTC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetTextColor(hItem, 0x00400080);
    TEXT_SetText(hItem, "00:00:00");
    //
    // Initialization of 'Text_Clock'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "00:00:00");
    TEXT_SetTextColor(hItem, 0x00A00000);
    //
    // Initialization of 'Text_Note'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "");
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'Text_State'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextColor(hItem, 0x0000FF00);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "");
    //
    // Initialization of 'Button_Set_Clock'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetText(hItem, "Set Clock");
    BUTTON_SetFont(hItem, GUI_FONT_8X18);
    //
    // Initialization of 'Text_GPS_Signal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");
    //
    // Initialization of 'Button_Set_UTC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, GUI_FONT_8X16_ASCII);
    BUTTON_SetText(hItem, "UTC");
    //
    // Initialization of 'Text_UTC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "UTC");
    TEXT_SetTextColor(hItem, 0x00400040);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Block'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "X");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, 0x000000FF);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem_TEXT_RTC = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    hItem_TEXT_Clock = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    hItem_TEXT_Note = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    hItem_TEXT_State = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    hItem_TEXT_GPS_Signal = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    hItem_TEXT_UTC = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		hItem_Text_Block = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		if(sett_store.mode_rtc == MODE_RTC_BLOCK){TEXT_SetText(hItem_Text_Block, "X");}
		else if(sett_store.mode_rtc == MODE_RTC_TEST){TEXT_SetText(hItem_Text_Block, "T");}
		else {TEXT_SetText(hItem_Text_Block, "");}
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button_Return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_RETURN);
				//DEBUG("Button_Return!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_Save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_SAVE);
				//DEBUG("Button_Save!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_Down'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_DOWN);
				//DEBUG("Button_Down!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_Right'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_RIGHT);
				//DEBUG("Button_Right!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button_Left'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_LEFT);
				//DEBUG("Button_Left!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button_Up'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_UP);
				//DEBUG("Button_Up!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button_Set_RTC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_SET_RTC);
				//DEBUG("Button_Set_RTC!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button_Set_Clock'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_SET_CLOCK);
				//DEBUG("Button_Set_Clock!\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'Button_Set_UTC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        Callback_Buttons(Buttons_SET_UTC_DOWN);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //Callback_Buttons(Buttons_SET_UTC_UP);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/*********************************************************************
*
*       MainTask
*/
void MainTask(void) {
	GUI_Init();

#if GUI_WINSUPPORT
	WM_SelectWindow(CreateWindow());
	GUI_Exec();
#endif

	while (1) {
		GUI_Delay(50);

		//ID_TEXT_0

	}
}

// USER END

/*************************** End of file ****************************/
